solutions = [
  {
    "name": "src",
    "url": "https://webrtc.googlesource.com/src.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_vars": {
      "checkout_android": False,
      "checkout_instrumented_libraries": False,
      "checkout_fuchsia": False,
      "checkout_fuzzer": False,
      "download_remoteexec_cfg": False,
      "checkout_ios": False,
    },
    "custom_deps": {
      "src/base": None,
      # "src/testing": None,
      "src/buildtools/reclient": None,
      "src/third_party/rust-toolchain": None,
      "src/third_party/clang-format/script": None,
      "src/third_party/test_fonts/test_fonts": None,
      "src/tools/resultdb": None,
      "src/third_party/breakpad/breakpad": None,
      "src/third_party/catapult": None,
      "src/third_party/ced/src": None, # Might be needed?  Need to test.
      "src/third_party/colorama/src": None,
      "src/third_party/flatbuffers/src": None,
      "src/third_party/grpc/src": None,
      "src/third_party/fontconfig/src": None,
      "src/third_party/freetype/src": None,
      "src/third_party/harfbuzz-ng/src": None,
      "src/third_party/google_benchmark/src": None,
      "src/third_party/gtest-parallel": None,
      "src/third_party/google-truth/src": None,
      "src/third_party/googletest/src": None,
      "src/third_party/jdk/current": None, # Prevent some hook even on linux?
      "src/third_party/jsoncpp/source": None,
      "src/third_party/libFuzzer/src": None,
      "src/third_party/fuzztest/src": None,
      "src/third_party/perfetto": None,
      "src/third_party/protobuf-javascript/src": None,
      "src/tools/luci-go": None,
    },
  },
]
